# Generated by Django 5.0.1 on 2024-02-16 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_groups_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 16, 11, 17, 40, 531025, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
