# Generated by Django 5.0.1 on 2024-03-01 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_onetimepassword_created_at_usersession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onetimepassword",
            old_name="user_agent",
            new_name="session_id",
        ),
        migrations.RenameField(
            model_name="usersession",
            old_name="user_agent",
            new_name="session_id",
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 1, 5, 21, 32, 344788, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
