# Generated by Django 5.0.1 on 2024-04-20 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_permission_alter_onetimepassword_created_at_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 20, 8, 50, 35, 883692, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(related_name="roles", to="users.permission"),
        ),
    ]
