# Generated by Django 5.0.1 on 2024-04-20 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_onetimepassword_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.AddField(
            model_name="role",
            name="permission",
            field=models.ManyToManyField(related_name="roles", to="users.permission"),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 20, 8, 59, 21, 269037, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
