# Generated by Django 5.0.1 on 2024-04-20 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_role_permissions_role_permission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="permission",
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 20, 9, 1, 4, 855998, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
