# Generated by Django 5.0.1 on 2024-04-20 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_role_permission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permission",
            field=models.ManyToManyField(related_name="roles", to="users.permission"),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 20, 9, 3, 3, 298069, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
