# Generated by Django 5.0.1 on 2024-04-20 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_role_permission_alter_onetimepassword_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="permission",
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(to="users.permission"),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 20, 9, 7, 42, 670455, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
