# Generated by Django 5.0.1 on 2024-04-21 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_role_permission_role_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 21, 19, 22, 42, 14731, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
