# Generated by Django 5.0.1 on 2024-04-21 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_onetimepassword_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 21, 19, 29, 34, 244838, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
