# Generated by Django 5.0.1 on 2024-04-21 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_onetimepassword_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(to="users.role"),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 21, 19, 32, 29, 388932, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
