# Generated by Django 5.0.1 on 2024-05-03 12:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_roles_alter_onetimepassword_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 12, 17, 28, 380302, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="LogUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_name", models.CharField(max_length=200)),
                (
                    "called_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 5, 3, 12, 17, 28, 381338, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
