# Generated by Django 5.0.1 on 2024-05-03 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_onetimepassword_created_at_logunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logunit",
            name="called_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 12, 17, 56, 932772, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 12, 17, 56, 929770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
