# Generated by Django 5.0.1 on 2024-05-05 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_logunit_called_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="from_oauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 5, 13, 1, 19, 204376, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
